<link rel="icon" type="image/png" sizes="32x32" href="https://useritium.fr/assets/tyrolium-ui/projects/onglets/Useritium-32x.png" />
<link rel="icon" type="image/png" sizes="16x16" href="https://useritium.fr/assets/tyrolium-ui/projects/onglets/Useritium-16x.png" />
<link rel="apple-touch-icon" sizes="180x180" href="https://useritium.fr/assets/tyrolium-ui/projects/onglets/Useritium-180x.png" />

<meta charset="utf-8">
<meta name="robots" content="noindex, nofollow">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<meta name="title" content="Dashboard - Useritium">
<meta name="description" content="Accédez à votre espace personnel Useritium : gérez votre compte, vos services et vos produits Tyrolium depuis votre dashboard."/>
<meta property="og:title" content="Dashboard - Useritium"/>
<meta property="og:type" content="website"/>
<meta property="og:url" content="https://dashboard.useritium.fr/"/>
<meta property="og:image" content="https://useritium.fr/assets/tyrolium-ui/projects/Useritium.png"/>
<meta property="og:description" content="Accédez à votre espace personnel Useritium : gérez votre compte, vos services et vos produits Tyrolium depuis votre dashboard."/>