<?php if($page ==2 || $page == 4 || $page == 5){ ?>
      <nav class="d-flex align-items-center justify-content-between">
            <a id="logo" href="https://useritium.fr" style="
                        text-align: center;
                        width: 100%;
                        font-family: 'Inter', sans-serif;
                        text-transform: uppercase;
                        font-size: 18px;
                        letter-spacing: 3px;
                        font-weight: bold;">
                Useritium <small style="font-size: 10px">Par Tyrolium</small></a>
        </nav>
        
<?php } ?>
