<section id="panel-game">
    <h3 class="title-morph">Vos jeux</h3>
    <div class="flex-container">

            <div class="game-back" onclick="redirectPanel('https://tyrociel.fr/')">
                <div class="picture">
                    <img class="img-fluid" src="assets/icone/add.png">
                </div>
                
                <div class="team-content">
                    <h3 class="name">Plus de jeux</h3>
                </div>
            </div>

            <div class="game-back"  onclick="redirectPanel('https://www.tyroserv.fr/')">
                <div class="picture">
                    <img class="img-fluid" src="http://localhost:9006/assets/tyrolium-ui/projects/TyroServ.png">
                </div>
                
                <div class="team-content">
                    <h3 class="name">TyroServ</h3>
                    <h4 class="title">By TyroServ</h4>
                </div>
            </div>

            <div class="game-back"  onclick="redirectPanel('https://themaxium69.github.io/Flappium/')">
                <div class="picture">
                    <img class="img-fluid" src="assets/game/flappium.png">
                </div>
                
                <div class="team-content">
                    <h3 class="name">Flappium</h3>
                    <h4 class="title">By Tyrolium</h4>
                </div>
            </div>

            <div class="game-back" onclick="redirectPanel('https://themaxium69.github.io/Echec-ium/')">
                <div class="picture">
                    <img class="img-fluid" src="assets/game/Echec-ium.png">
                </div>
                
                <div class="team-content">
                    <h3 class="name">Echec-ium</h3>
                    <h4 class="title">By Tyrolium</h4>
                </div>
            </div>

    </div>

</section>
